export const programs = [
  {
    id: "checkout-reliability",
    name: "Checkout Reliability",
    portfolio: "Marketplace Payments",
    owner: "Chris L.",
    sponsor: "Engineering Operations",
    cadence: "Monday health probe",
    refresh: "Mon 8:00 AM",
    confidence: 82,
    releaseTarget: "Jun 28",
    summary:
      "Reliability work is moving, but fraud handoff and rollback verification need manager attention before Thursday.",
    metrics: [
      {
        label: "Initiatives",
        value: "7",
        delta: "+2",
        tone: "good",
        note: "Two moved from watch to on track after PR merges.",
      },
      {
        label: "Open blockers",
        value: "4",
        delta: "-1",
        tone: "good",
        note: "Payments auth dependency cleared Friday.",
      },
      {
        label: "Commitment risk",
        value: "31%",
        delta: "+0",
        tone: "watch",
        note: "Risk is concentrated in two stories.",
      },
      {
        label: "Reviewed signals",
        value: "46",
        delta: "+17",
        tone: "neutral",
        note: "PR, Jira, deploy, CI, meeting notes, and Notion signals reviewed.",
      },
    ],
    initiatives: [
      {
        key: "PAY-1842",
        name: "Payment authorization cleanup",
        lead: "Backend Platform",
        progress: 76,
        planned: 72,
        status: "on-track",
        evidence: ["PR #481", "PR #488", "CI 8829"],
        summary: "Merged token refresh changes and cleared two failing integration tests.",
      },
      {
        key: "REL-2204",
        name: "Checkout rollback automation",
        lead: "Reliability",
        progress: 48,
        planned: 62,
        status: "watch",
        evidence: ["PR #488", "Runbook draft", "Notion runbook"],
        summary: "Rollback path is coded, but deployment verification has not started.",
      },
      {
        key: "OBS-1047",
        name: "Order trace observability",
        lead: "Frontend Core",
        progress: 61,
        planned: 58,
        status: "on-track",
        evidence: ["PR #492", "Deploy 06.15"],
        summary: "Trace IDs now appear on checkout and receipt surfaces.",
      },
      {
        key: "FRAUD-612",
        name: "Risk score handoff",
        lead: "Fraud Systems",
        progress: 33,
        planned: 55,
        status: "at-risk",
        evidence: ["PR #496", "Slack risk thread", "Meeting notes"],
        summary: "API contract changed twice and PRs do not map to committed sprint scope.",
      },
    ],
    readout: [
      "Payment auth is no longer the main blocker. Risk has shifted to rollback verification and fraud score handoff.",
      "Two initiatives show Jira progress ahead of code evidence. Both should be reviewed before Thursday status.",
      "The executive summary should stay green-yellow, not red. The risk is containable if ownership is clarified by Wednesday.",
    ],
    weekChanges: [
      {
        type: "Risk shifted",
        tone: "risk",
        title: "Main risk moved from payments auth to fraud handoff",
        summary: "Payment cleanup is now evidenced by merged PRs, while FRAUD-612 picked up a contract mismatch after commitment.",
        previous: "PAY-1842 blocked",
        current: "FRAUD-612 at risk",
        confidence: "High confidence",
        explanation: [
          "PAY-1842 has two merged PRs and a linked deploy reference, so the old blocker is no longer the highest management concern.",
          "PR #496 implements v3 fraud mapping while the Jira acceptance criteria still reference the v2 response contract.",
          "Meeting notes do not name a decision owner for the contract change, which is why this needs human follow-up.",
        ],
        sources: ["PAY-1842", "PR #481", "PR #496", "Meeting Notes"],
        action: "Confirm Fraud Systems ownership before Wednesday and rebaseline the commitment if the v3 contract is real scope.",
      },
      {
        type: "Evidence gap",
        tone: "watch",
        title: "Rollback moved from implementation to validation risk",
        summary: "REL-2204 has code evidence now, but release confidence is still weak because staging validation is missing.",
        previous: "Implementation open",
        current: "Validation missing",
        confidence: "Medium confidence",
        explanation: [
          "Rollback command scaffolding appears complete based on PR #488.",
          "CI run 8831 does not prove the rollback path works end to end in staging.",
          "The Notion runbook exists, but its validation checklist is still empty.",
        ],
        sources: ["REL-2204", "PR #488", "CI run 8831", "Notion runbook"],
        action: "Add staging rollback proof to the Thursday readiness review before calling this on track.",
      },
      {
        type: "Signal improved",
        tone: "good",
        title: "Observability gained release evidence",
        summary: "Order trace work moved from planned implementation to deployed feature-flag evidence.",
        previous: "Planned",
        current: "Deployed in staging",
        confidence: "High confidence",
        explanation: [
          "OBS-1047 has a deploy event for checkout trace propagation behind a feature flag.",
          "PR #492 links the implementation to checkout and receipt surfaces.",
          "Retry and refund paths are still not covered, so the status stays on track rather than complete.",
        ],
        sources: ["OBS-1047", "PR #492", "Deploy 06.15"],
        action: "Keep this green-yellow and ask whether retry/refund trace coverage is release-blocking.",
      },
    ],
    reviewQueue: [
      {
        title: "Confirm Fraud Systems owner",
        owner: "Chris",
        body: "Meeting notes and Slack agree that FRAUD-612 lacks a named decision owner.",
      },
      {
        title: "Ask for rollback validation proof",
        owner: "Reliability",
        body: "Implementation evidence exists, but CI and deploy signals do not yet show end-to-end validation.",
      },
      {
        title: "Prepare Thursday status narrative",
        owner: "Chris",
        body: "Keep the brief focused on release confidence, not another project-plan review.",
      },
    ],
    conflicts: [
      {
        title: "Jira progress is ahead of implementation evidence",
        priority: "High",
        system: "FRAUD-612 appears planned against the original v2 response contract.",
        evidence: "PR #496 implements v3 mapping and the meeting notes show the owner decision is still open.",
        question: "TPM question: should this commitment be rebaselined before Thursday status?",
        sources: ["FRAUD-612", "PR #496", "Meeting Notes"],
      },
      {
        title: "Merged code does not equal release confidence",
        priority: "Medium",
        system: "REL-2204 has implementation work merged and appears close to done.",
        evidence: "CI and Notion show no completed staging validation checklist for the rollback path.",
        question: "TPM question: is rollback validation release-blocking or a post-merge follow-up?",
        sources: ["REL-2204", "CI run 8831", "Notion runbook"],
      },
    ],
    digest: [
      {
        title: "Completed last week",
        items: [
          "PAY-1842 merged PR #481 and PR #488 for token refresh cleanup.",
          "OBS-1047 deployed trace ID propagation behind a feature flag.",
          "REL-2204 completed rollback command scaffolding, but validation remains open.",
        ],
      },
      {
        title: "Plan for this week",
        items: [
          "Finish rollback verification in staging and publish operational runbook.",
          "Resolve FRAUD-612 API contract mismatch with Fraud Systems.",
          "Add checkout trace coverage to the Thursday readiness review.",
        ],
      },
      {
        title: "Slipped commitments",
        items: [
          "FRAUD-612 was forecast at 55 percent complete, but code evidence supports roughly 33 percent.",
          "REL-2204 verification was planned for Friday and has no CI or deploy signal yet.",
        ],
      },
    ],
    drafts: {
      executive: {
        title: "Executive summary",
        paragraphs: [
          "Checkout Reliability remains directionally on track, with one dependency that needs management attention this week.",
          "Payment authorization cleanup shipped as planned. Rollback automation is progressing, but validation is now the critical path. Fraud score handoff is the only initiative trending at risk due to repeated API contract changes.",
          "Recommended action: confirm Fraud Systems ownership by Wednesday and keep rollback verification in the Thursday readiness review.",
        ],
      },
      engineering: {
        title: "Engineering update",
        paragraphs: [
          "This week's priority is converting merged code into verified release confidence.",
          "Backend Platform should close staging validation for REL-2204. Fraud Systems and Checkout need one contract decision on FRAUD-612 before additional implementation work starts.",
          "Evidence reviewed: Jira issues PAY-1842, REL-2204, OBS-1047, FRAUD-612; PR #481, #488, #496; deploy checkout-2026.06.15.",
        ],
      },
      jira: {
        title: "Suggested system-of-record note",
        paragraphs: [
          "Status: Watch.",
          "Update: Payment auth cleanup shipped and observability work progressed. Rollback automation implementation is complete but validation is pending. Fraud handoff has slipped because API contract changes are not reflected in sprint estimates.",
          "Risks: FRAUD-612 ownership and REL-2204 validation. Next checkpoint: Thursday readiness review.",
        ],
      },
    },
    risks: [
      {
        id: "risk-1",
        severity: "critical",
        status: "blocked",
        title: "Fraud score API contract changed after sprint commitment",
        owner: "Fraud Systems",
        probability: "High",
        impact: "Release confidence",
        body: "The committed story still assumes v2 response fields, while PR #496 implements v3 mapping. Jira progress has not been adjusted.",
        action: "Schedule owner decision before Wednesday noon.",
        sources: ["FRAUD-612", "PR #496", "Meeting notes", "Slack #checkout-risk"],
      },
      {
        id: "risk-2",
        severity: "watch",
        status: "watch",
        title: "Rollback implementation lacks staging proof",
        owner: "Reliability",
        probability: "Medium",
        impact: "Operational readiness",
        body: "Code has landed, but no CI run or deploy evidence confirms the rollback path works end to end.",
        action: "Add staging validation to Thursday review.",
        sources: ["REL-2204", "PR #488", "CI run 8831", "Notion runbook"],
      },
      {
        id: "risk-3",
        severity: "watch",
        status: "watch",
        title: "Trace coverage is good but not release-wide",
        owner: "Frontend Core",
        probability: "Medium",
        impact: "Incident debugging",
        body: "Checkout and receipt flows are covered. Refund and retry paths are not linked to order trace IDs.",
        action: "Confirm whether retry coverage is release-blocking.",
        sources: ["OBS-1047", "PR #492", "Deploy 06.15"],
      },
      {
        id: "risk-4",
        severity: "critical",
        status: "critical",
        title: "Sprint estimate drift is concentrated in two owners",
        owner: "Engineering Leads",
        probability: "High",
        impact: "Sprint forecast",
        body: "Two stories show high activity but low closure. The signal suggests hidden work or underestimated implementation paths.",
        action: "Rebaseline story points before next sprint planning.",
        sources: ["PAY board", "Git activity", "Sprint 26.12"],
      },
    ],
    evidence: [
      {
        time: "08:00",
        source: "Jira",
        title: "PAY-1842 moved to Done",
        body: "Sprint board shows payment auth cleanup complete with two linked PRs and one deploy reference.",
        confidence: "High",
      },
      {
        time: "08:04",
        source: "GitHub",
        title: "PR #496 conflicts with FRAUD-612 scope",
        body: "Diff references v3 risk mapping, but Jira acceptance criteria still describe v2 response fields.",
        confidence: "Medium",
      },
      {
        time: "08:08",
        source: "CI",
        title: "Rollback validation missing",
        body: "REL-2204 has merged implementation code, but no green staging validation run is linked.",
        confidence: "High",
      },
      {
        time: "08:11",
        source: "Deploy",
        title: "Trace IDs deployed behind feature flag",
        body: "Checkout trace propagation is live in staging behind checkout_trace_context.",
        confidence: "High",
      },
      {
        time: "08:14",
        source: "Meeting Notes",
        title: "Fraud ownership unresolved in lead sync",
        body: "The Monday lead sync notes show no named owner for the v3 risk score contract decision.",
        confidence: "Medium",
      },
      {
        time: "08:17",
        source: "Notion",
        title: "Rollback runbook lacks validation checklist",
        body: "The draft runbook covers commands and contacts, but the staging validation checklist is still empty.",
        confidence: "Medium",
      },
    ],
    signals: [
      { source: "Jira", detail: "Initiatives and committed scope", state: "Read only", strength: 94 },
      { source: "Git", detail: "PRs, diffs, owners, changed files", state: "Simulated", strength: 88 },
      { source: "CI", detail: "Test and validation evidence", state: "Simulated", strength: 71 },
      { source: "Slack", detail: "Risk comments and owner asks", state: "Optional", strength: 46 },
      { source: "Meeting Notes", detail: "Lead syncs, standups, and review decisions", state: "Simulated", strength: 68 },
      { source: "Notion", detail: "Runbooks, specs, and release checklists", state: "Simulated", strength: 63 },
      { source: "Output", detail: "Brief, system note, exec summary", state: "Human reviewed", strength: 100 },
    ],
  },
  {
    id: "rider-identity",
    name: "Rider Identity Refresh",
    portfolio: "Account Platform",
    owner: "Chris L.",
    sponsor: "Identity Core",
    cadence: "Thursday readiness review",
    refresh: "Mon 8:00 AM",
    confidence: 74,
    releaseTarget: "Jul 08",
    summary: "Identity refresh is healthier than last week, with Android adoption as the only active watch item.",
    metrics: [
      {
        label: "Initiatives",
        value: "5",
        delta: "+0",
        tone: "neutral",
        note: "Stable scope for the last two weeks.",
      },
      {
        label: "Open blockers",
        value: "2",
        delta: "-3",
        tone: "good",
        note: "Legal copy and auth token issues cleared.",
      },
      {
        label: "Commitment risk",
        value: "24%",
        delta: "-8",
        tone: "good",
        note: "Risk improved after mobile SDK merge.",
      },
      {
        label: "Reviewed signals",
        value: "33",
        delta: "+11",
        tone: "neutral",
        note: "CI, branch, Slack, meeting notes, and Notion checklist signals reviewed.",
      },
    ],
    initiatives: [
      {
        key: "ID-310",
        name: "Identity consent copy",
        lead: "Product Systems",
        progress: 88,
        planned: 82,
        status: "on-track",
        evidence: ["Legal packet", "PR #768", "Notion checklist"],
        summary: "Legal-approved strings landed for web and iOS.",
      },
      {
        key: "ID-344",
        name: "Session token rotation",
        lead: "Identity Core",
        progress: 71,
        planned: 68,
        status: "on-track",
        evidence: ["PR #771", "CI 4412"],
        summary: "Rotation logic merged with passing integration tests.",
      },
      {
        key: "ID-351",
        name: "Android SDK rollout",
        lead: "Mobile",
        progress: 42,
        planned: 55,
        status: "watch",
        evidence: ["PR #777", "Review queue", "Meeting notes"],
        summary: "SDK published, but adoption branch is still behind target.",
      },
    ],
    readout: [
      "Identity refresh is healthier than last week and no longer needs executive escalation.",
      "Android SDK adoption should be watched because it is the only stream with code lagging Jira status.",
      "The Thursday readout should focus on release readiness, not scope debate.",
    ],
    weekChanges: [
      {
        type: "Signal improved",
        tone: "good",
        title: "Legal copy moved out of escalation",
        summary: "Consent copy now has legal-approved evidence and linked implementation work across web and iOS.",
        previous: "Legal blocker",
        current: "Approved copy",
        confidence: "High confidence",
        explanation: [
          "ID-310 moved to Done with legal-approved copy attached.",
          "PR #768 shows implementation work for web and iOS copy surfaces.",
          "The remaining content risk is localization, not legal approval.",
        ],
        sources: ["ID-310", "Legal packet", "PR #768", "Notion checklist"],
        action: "Do not escalate legal copy; track localization evidence separately.",
      },
      {
        type: "Watch item",
        tone: "watch",
        title: "Android adoption became the only release watch",
        summary: "Most streams gained evidence, but Android still trails plan due to review capacity.",
        previous: "Multiple blockers",
        current: "One mobile watch",
        confidence: "Medium confidence",
        explanation: [
          "Session rotation has passing CI and no longer needs manager attention.",
          "ID-351 remains one review cycle behind target despite Jira readiness looking healthy.",
          "Meeting notes call out reviewer capacity as the limiting factor.",
        ],
        sources: ["ID-351", "PR #777", "CI 4412", "Meeting Notes"],
        action: "Ask Mobile for reviewer availability today and avoid broad executive escalation unless the review slips again.",
      },
      {
        type: "Evidence gap",
        tone: "watch",
        title: "Localization is still outside the release checklist",
        summary: "Launch content appears approved in Jira, but Notion does not show localized strings attached.",
        previous: "Copy approval pending",
        current: "Localization missing",
        confidence: "Medium confidence",
        explanation: [
          "ID-310 is marked done because English copy has been approved.",
          "The Notion release checklist does not include localized strings.",
          "This may be rollout completeness rather than launch-blocking scope, so it needs human confirmation.",
        ],
        sources: ["ID-310", "Notion", "Release checklist"],
        action: "Confirm whether localization is required for launch readiness or can be tracked as rollout follow-up.",
      },
    ],
    reviewQueue: [
      {
        title: "Confirm Android reviewer capacity",
        owner: "Chris",
        body: "Meeting notes call out review bandwidth as the remaining adoption risk.",
      },
      {
        title: "Attach localization evidence",
        owner: "Product Systems",
        body: "Notion has approved English copy, but localized strings are still missing from the checklist.",
      },
      {
        title: "Prepare readiness readout",
        owner: "Chris",
        body: "Frame the update as release readiness with one watch item, not a full planning discussion.",
      },
    ],
    conflicts: [
      {
        title: "Jira readiness is stronger than branch evidence",
        priority: "High",
        system: "ID-351 is tracking toward the planned release checkpoint.",
        evidence: "PR #777 has unresolved reviews and meeting notes mention reviewer capacity risk.",
        question: "TPM question: does Android adoption need escalation today or can it wait for Thursday?",
        sources: ["ID-351", "PR #777", "Meeting Notes"],
      },
      {
        title: "Launch content appears approved but not complete",
        priority: "Medium",
        system: "ID-310 is marked done after legal-approved copy landed.",
        evidence: "The Notion release checklist does not include localized strings.",
        question: "TPM question: is localization required for launch readiness or just rollout completeness?",
        sources: ["ID-310", "Notion", "Release checklist"],
      },
    ],
    digest: [
      {
        title: "Completed last week",
        items: [
          "Consent copy landed across web and iOS.",
          "Session rotation tests passed.",
          "Legal blocker cleared.",
        ],
      },
      {
        title: "Plan for this week",
        items: [
          "Finish Android SDK adoption.",
          "Run staged identity refresh rollout.",
          "Prepare Thursday go/no-go summary.",
        ],
      },
      {
        title: "Slipped commitments",
        items: ["Android adoption branch remains one review cycle behind."],
      },
    ],
    drafts: {
      executive: {
        title: "Executive summary",
        paragraphs: [
          "Rider Identity Refresh is on track with one mobile adoption watch item.",
          "Legal copy and token rotation have cleared. Android SDK adoption remains behind target but is not yet release-blocking.",
        ],
      },
      engineering: {
        title: "Engineering update",
        paragraphs: [
          "Keep Android SDK adoption on the critical path.",
          "All other streams have enough evidence for Thursday readiness.",
        ],
      },
      jira: {
        title: "Suggested system-of-record note",
        paragraphs: [
          "Status: On track.",
          "Update: Legal copy and token rotation cleared. Android adoption remains the only watch item.",
        ],
      },
    },
    risks: [
      {
        id: "risk-5",
        severity: "watch",
        status: "watch",
        title: "Android adoption branch is behind",
        owner: "Mobile",
        probability: "Medium",
        impact: "Release readiness",
        body: "Branch is one review cycle behind target despite Jira showing planned progress.",
        action: "Confirm reviewer availability today.",
        sources: ["ID-351", "PR #777", "Meeting notes"],
      },
      {
        id: "risk-6",
        severity: "watch",
        status: "watch",
        title: "Rollout copy needs final localization pass",
        owner: "Product Systems",
        probability: "Low",
        impact: "Launch content",
        body: "English copy is approved. Localized strings are not attached to the release checklist.",
        action: "Attach localization evidence before Thursday.",
        sources: ["ID-310", "Release checklist", "Notion"],
      },
    ],
    evidence: [
      {
        time: "08:00",
        source: "Jira",
        title: "ID-310 moved to Done",
        body: "Legal-approved consent copy is attached to the issue.",
        confidence: "High",
      },
      {
        time: "08:06",
        source: "GitHub",
        title: "ID-351 branch behind target",
        body: "Android adoption branch has two unresolved reviews.",
        confidence: "Medium",
      },
      {
        time: "08:09",
        source: "CI",
        title: "Session rotation tests green",
        body: "Integration suite passed on commit a82c1.",
        confidence: "High",
      },
      {
        time: "08:12",
        source: "Meeting Notes",
        title: "Android reviewer availability called out",
        body: "Thursday readiness prep notes mention reviewer capacity as the remaining adoption risk.",
        confidence: "Medium",
      },
      {
        time: "08:16",
        source: "Notion",
        title: "Localization checklist incomplete",
        body: "The release checklist page has English copy approved, but localized strings are not attached.",
        confidence: "Medium",
      },
    ],
    signals: [
      { source: "Jira", detail: "Release checklist and scope", state: "Read only", strength: 89 },
      { source: "Git", detail: "SDK branches and PRs", state: "Simulated", strength: 77 },
      { source: "CI", detail: "Integration tests", state: "Simulated", strength: 81 },
      { source: "Slack", detail: "Reviewer asks and launch-channel risk comments", state: "Optional", strength: 38 },
      { source: "Meeting Notes", detail: "Readiness prep and reviewer risks", state: "Simulated", strength: 62 },
      { source: "Notion", detail: "Release checklist and localization notes", state: "Simulated", strength: 66 },
      { source: "Output", detail: "Thursday readiness summary", state: "Human reviewed", strength: 100 },
    ],
  },
];

export const views = [
  { id: "overview", label: "Overview" },
  { id: "digest", label: "Weekly Brief" },
  { id: "risks", label: "Attention Needed" },
  { id: "evidence", label: "Evidence" },
];

export const statuses = {
  "on-track": "On track",
  watch: "Watch",
  "at-risk": "At risk",
  blocked: "Blocked",
  critical: "Critical",
};
